// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvnJiHZmUTOtkzAODHeKxIAeoLaPoy3gg',
    appId: '1:1025135011021:web:383f00c7077ffa32e33584',
    messagingSenderId: '1025135011021',
    projectId: 'stockr-ojt',
    authDomain: 'stockr-ojt.firebaseapp.com',
    storageBucket: 'stockr-ojt.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeXe3GDSYxVvIaJxAnv48kA6msKH_XDKM',
    appId: '1:1025135011021:android:bb90908d0a713260e33584',
    messagingSenderId: '1025135011021',
    projectId: 'stockr-ojt',
    storageBucket: 'stockr-ojt.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVH70KPnS6ddNMT6st-ac3J2n-p4H1-AI',
    appId: '1:1025135011021:ios:1ebeb6f2b78b6a35e33584',
    messagingSenderId: '1025135011021',
    projectId: 'stockr-ojt',
    storageBucket: 'stockr-ojt.firebasestorage.app',
    iosBundleId: 'com.example.stockrOjt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVH70KPnS6ddNMT6st-ac3J2n-p4H1-AI',
    appId: '1:1025135011021:ios:1ebeb6f2b78b6a35e33584',
    messagingSenderId: '1025135011021',
    projectId: 'stockr-ojt',
    storageBucket: 'stockr-ojt.firebasestorage.app',
    iosBundleId: 'com.example.stockrOjt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvnJiHZmUTOtkzAODHeKxIAeoLaPoy3gg',
    appId: '1:1025135011021:web:023bc913d513c053e33584',
    messagingSenderId: '1025135011021',
    projectId: 'stockr-ojt',
    authDomain: 'stockr-ojt.firebaseapp.com',
    storageBucket: 'stockr-ojt.firebasestorage.app',
  );
}
